/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package okay;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test
    public void testRoll() {
        ArrayList<Integer> rolls = Library.roll(4);
        assertEquals(4, rolls.size());
        for (int roll : rolls) {
            assertTrue(roll >= 1 && roll <= 6);
        }
    }

    @Test
    public void testContainsDuplicates() {
        assertTrue(Library.containsDuplicates(new int[] { 1, 2, 3, 4, 5, 6, 1 }));
        assertFalse(Library.containsDuplicates(new int[] { 1, 2, 3, 4, 5, 6, 7 }));
    }

    @Test
    public void testCalculateAverage() {
        assertEquals(4.0, Library.calculateAverage(new int[] { 1, 2, 3, 4, 5, 6, 7 }), 0.0001);
        assertEquals(6.0, Library.calculateAverage(new int[] { 6, 6, 6, 6, 6, 6 }), 0.0001);
    }

    @Test
    public void testGetLowestAverageArray() {
        int[][] arr = {
                { 66, 64, 58, 65, 71, 57, 60 },
                { 57, 65, 65, 70, 72, 65, 51 },
                { 55, 54, 60, 53, 59, 57, 61 },
                { 65, 56, 55, 52, 55, 62, 57 }
        };
        assertArrayEquals(new int[] { 55, 54, 60, 53, 59, 57, 61 }, Library.getLowestAverageArray(arr));
    }
}
